name: "Build Uberhand"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  Build-Uberhand:
    name: "Release"
    runs-on: "ubuntu-latest"
    container: "ghcr.io/irneracoonovich/devkita64:latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          generate_release_notes: true
          files: ovlmenu.ovl