name: "Test Uberhand"

on:
  pull_request:
  workflow_dispatch:

jobs:
  Test-Uberhand:
    name: "Build Test"
    runs-on: "ubuntu-latest"
    container: "ghcr.io/irneracoonovich/devkita64:latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make
